"""remove privacy statement from preferences

Revision ID: 2cdae5514250
Revises: 9ceea25973ba
Create Date: 2019-08-21 11:24:55.508891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdae5514250'
down_revision = '9ceea25973ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'privacy_statement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('privacy_statement', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
