"""empty message

Revision ID: 66ad5bfcaa78
Revises: 0e1b44463cc0
Create Date: 2019-08-15 12:09:35.550643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ad5bfcaa78'
down_revision = '0e1b44463cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'copy_email_task_id')
    op.drop_column('enquiries', 'confirmation_email_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('confirmation_email_task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('copy_email_task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
