"""empty message

Revision ID: 6e0d84607cab
Revises: d05bfb05489b
Create Date: 2019-07-15 10:41:47.190567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0d84607cab'
down_revision = 'd05bfb05489b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'sale')
    # ### end Alembic commands ###
