"""empty message

Revision ID: 884c94e491c3
Revises: 7f9971c51679
Create Date: 2019-12-05 15:16:38.137728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884c94e491c3'
down_revision = '7f9971c51679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    # ### end Alembic commands ###
