"""empty message

Revision ID: 9ceea25973ba
Revises: 8158e1b4904c
Create Date: 2019-08-15 13:12:32.377539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ceea25973ba'
down_revision = '8158e1b4904c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('shop', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'shop')
    # ### end Alembic commands ###
