"""empty message

Revision ID: c573be969f88
Revises: 884c94e491c3
Create Date: 2019-12-07 12:24:59.111892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c573be969f88'
down_revision = '884c94e491c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'value')
    # ### end Alembic commands ###
